### ISSUE TITLE
Pre-launch issues

### ISSUE THREAD

**Issue by huijing** [interledger/interledger.org-v4#4]
As the site is still undergoing a lot of content changes, it is easier to track all the issues in this meta-issue until we actually go live. Once we go live, all typical SOP (branching off and making changes via PR) will resume. For now, we are taking "The Cowboy Approach", at least, until the content has been finalised such that we can at least finalise how the visuals should look when presenting said content.

**Tasks**
- [x] #2 
- [x] #3 
- [x] [Implement theme switching on pages and articles](https://github.com/interledger/interledger.org-v4/commit/be5a275a7925d2b7e14c6f7661b519bf5262fe79)
- [x] [Change site header and footer to neutral colour palette](https://github.com/interledger/interledger.org-v4/commit/be5a275a7925d2b7e14c6f7661b519bf5262fe79)
- [x] [Implement mailing list sign up](https://github.com/interledger/interledger.org-v4/commit/24dd25446a99ba9930246fdb945c782594440b98)
- [x] [Add placeholder grid for Art page](https://github.com/interledger/interledger.org-v4/commit/0c5b2d2798de0ce19f2f867016270d6f6e9e212c)
- [x] Rearrage Summit pages to cater for archiving past events
- [x] [Rework Card component implementation to better reflect current usage (cards with caption and without caption, add back card category for creation of view blocks)](https://github.com/interledger/interledger.org-v4/commit/0c5b2d2798de0ce19f2f867016270d6f6e9e212c)
- [x] Add quote source field to Blockquote component

**Comment by huijing** [comment]
We have launched.
